name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build:lib
      - run: npm run publish:lib
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@SachinShekhar'
      - run: npm ci
      - run: npm run build:lib
      - run: npm run publish:lib
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
