name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lib:build
      - run: npm run lib:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
